spring.application.name=spring-boot-course

spring.datasource.url=jdbc:postgresql://localhost:5332/amigos
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.ai.openai.api-key=${OPENAI_API_KEY:}
